# Streamlit UI 用の暫定しきい値。数値は現行 rules_v2.yaml の条件値を写経したものです。
# 将来的にチューニングしたらこのファイルを更新し、DSL 側では features.T_* として参照します。

const:
  wd14:
    questionable: 0.50
    explicit: 0.50
  qe:
    share_min: 0.55
  exposure:
    area:
      mid: 0.15
      high: 0.20
  sexual:
    main:
      strong: 0.60
  low_margin: 0.10
  minor:
    main: 0.30
    sit_enabled: 0.0
  suspect:
    explicit: 0.60
    questionable: 0.45
  coercion:
    pair: 0.55
    org: 0.95
    main_strict: 0.50
    pain_cnt: 1
    sub_min: 1
    uncon_min: 0.35
    force_org: 0.98
  bestiality:
    direct: 0.20
  animal:
    presence: 0.50
    fp_penalty: 0.80
  gore:
    main: 0.40
    density: 4.0
    topk: 0.70
    org: 0.70
    red: 0.85

minor:
  main: 0.30
  peak_conf:
    red: 0.30
  body_score:
    red: 0.70
  context_score:
    red: 0.80
  special_score:
    yellow: 0.35
  sit_enabled: 0.0
sexual:
  main:
    strong: 0.60
  intensity:
    red_high: 0.80
    red: 0.50
    orange: 0.40
    yellow: 0.30
    caution: 0.20
explicit:
  score:
    red: 0.50
    orange: 0.30
    yellow: 0.20
exposure:
  area:
    high: 0.20
    mid: 0.15
    low: 0.10
  count:
    high: 2
nsfw_rating:
  max:
    orange: 0.50
suspect:
  explicit: 0.60
  questionable: 0.45
coercion:
  pair: 0.55
  org: 0.95
  main_strict: 0.50
  pain_cnt: 1
  sub_min: 1
  uncon_min: 0.35
  force_org: 0.98
gore:
  main_gate: 0.30
  density_gate: 4.0
  topk_gate: 0.70
  org_gate: 0.70
  red_gate: 0.85
  peak_conf:
    warn: 0.20
  density:
    warn: 3
  intensity:
    red: 2.50
    orange: 2.00
animal:
  presence_gate: 0.35
  presence:
    yellow: 0.30
  fp_penalty: 0.80
bestiality:
  direct_gate: 0.20
  direct:
    red: 0.20
