models:
  wd14_repo: "SmilingWolf/wd-eva02-large-tagger-v3"

thresholds:
  wd14_questionable: 0.35
  wd14_explicit: 0.20
  wd14_minors_sum: 0.40
  gore_tag: 0.25
  gore_sum: 0.40
  gore_any: 0.30
  nsfw_margin_min: 0.00
  nsfw_ratio_min: 0.45
  nsfw_general_sum: 0.20
  exposure_mid: 0.30
  exposure_strong: 0.60
  exposure_risk: 0.60
  yellow_minor_hint: 0.20

minor_tags:
  - loli
  - shota
  - child
  - kid
  - newborn
  - baby
  - infant
  - toddler
  - preteen
  - teen
  - young
  - younger
  - adolescent
  - little_girl
  - little_boy
  - schoolgirl
  - schoolboy
  - school_uniform
  - randoseru
  - flat_chest
  - small_breasts
  - chibi

violence_tags:
  - gore
  - blood
  - guts
  - wound
  - severed_arm
  - severed_leg
  - severed_head
  - decapitation
  - disembowelment
  - dismemberment
  - guro
  - ryona
  - death
  - corpse
  - injury
  - cuts
  - bruise
  - scar
  - torture
  - whipping
  - burn
  - murder
  - strangulation
  - asphyxiation
  - drowning
  - electrocution
  - poison
  - stab
  - slash
  - gunshot
  - cannibalism
  - vore
  - mutilation
  - necrophilia
  - abuse
  - bullying
  - rape
  - execution
  - war
  - drug
  - pill
  - syringe
  - injection
  - marijuana
  - cocaine
  - heroin
  - meth
  - lsd
  - addiction

nsfw_general_tags:
  - nude
  - topless
  - bottomless
  - nipples
  - penis
  - testicles
  - pussy
  - clitoris
  - cameltoe
  - cleft_of_venus
  - futanari
  - anus
  - pubic_hair
  - uncensored
  - censored
  - mosaic_censoring
  - cum
  - pussy_juice
  - pee
  - scat
  - sex
  - vaginal
  - anal
  - oral
  - paizuri
  - fellatio
  - cunnilingus
  - penetration
  - masturbation
  - ejaculation
  - orgasm
  - group_sex
  - gangbang
  - orgy
  - rape
  - bondage
  - sex_toy
  - dildo
  - vibrator
  - object_insertion
  - bdsm
  - spanking
  - collar
  - leash
  - slave
  - lactation
  - pregnant

animal_abuse_tags:
  - animal_abuse
  - animal_cruelty
  - animal_blood
  - animal_gore
  - bestiality
  - zoophilia
  - zoosadism
  - animal_harm
  - animal_torture
  - dead_animal
  - taxidermy
  - animal_fight
  - animal_trap
  - animal_starvation
  - animal_neglect
  - feral_abuse
  - furry_bestiality
  - yiff
  - animal_corpse
  - hunting
  - dog
  - cat
  - horse
  - bird
  - rabbit
  - cow
  - pig
  - snake
  - insect
  - furry
  - wolf
  - fox
  - lion
  - tiger
  - bear
  - deer
  - sheep
  - goat
  - fish
  - reptile
  - amphibian
  - rodent
  - monkey
  - elephant
  - dragon
  - unicorn
  - pokemon
  - anthro
  - kemono

xsignals_weights:
  exposure_strong_weight: 1.0
  exposure_weak_weight: 0.6
  placement_rating_weight: 0.5
  placement_general_weight: 0.3
  placement_exposure_weight: 0.7
  placement_general_topk: 3

severity_priority:
  red: 3
  orange: 2
  yellow: 1

rule_titles:
  RED-201: "暴力・グロが疑われる"
  RED-301: "未成年の性的描写が疑われる"
  ORANGE-101: "18+でないチャンネルの成人向けコンテンツ"
  YELLOW-101: "軽度の露出"
  YELLOW-201: "若年寄りの特徴を含む"
