version: 2
dsl_mode: warn

rule_titles:
  RED-201: "暴力・グロが疑われる"
  RED-301: "未成年の性的描写が疑われる"
  ORANGE-101: "18+でないチャンネルの成人向けコンテンツ"
  YELLOW-101: "軽度の露出"
  YELLOW-201: "若年寄りの特徴を含む"
  RED-NSFW-101: "非NSFWチャンネルの性的表現"
  RED-MINOR-SEX-201: "未成年×性的"
  RED-MINOR-GORE-202: "未成年×流血/損壊"
  RED-ANIMAL-SEX-301: "動物×性的/獣姦"
  RED-ANIMAL-GORE-302: "動物×虐待/流血"
  RED-DISMEMBER-BLOOD-401: "欠損×出血"
  ORANGE-ADULT-SEX-DRUG-501: "成人×性的×薬物"
  ORANGE-MINOR-MILD-601: "未成年×軽微露出"

groups:
  nsfw_general:
    - bikini
    - lingerie
    - see_through
    - underboob
  animal_contexts:
    - animal_abuse
    - animal_harm
    - animal_gore
    - animal_cruelty
  animal_subjects:
    - dog
    - cat
    - horse
    - bird

features:
  nsfw_margin: "max(rating.explicit, rating.questionable) - max(rating.general, rating.sensitive)"
  animal_combo: "max('animal_contexts') * max('animal_subjects')"

rules:
  - id: ORANGE-101
    severity: orange
    priority: 10
    when: "(!channel.is_nsfw) && (nsfw_margin >= 0.10 || any('nsfw_general', gt=0.35))"
    reasons:
      - "margin={nsfw_margin:.2f}"
  - id: RED-ANIMAL-GORE-302
    severity: red
    priority: 20
    when: "max('animal_contexts') >= 0.25 || (animal_combo >= 0.04)"
    reasons:
      - "ctx={max('animal_contexts'):.2f}"
      - "combo={animal_combo:.2f}"
    stop: true

models:
  wd14_repo: "SmilingWolf/wd-eva02-large-tagger-v3"

thresholds:
  wd14_questionable: 0.35
  wd14_explicit: 0.20
  wd14_minors_sum: 0.40
  gore_tag: 0.25
  gore_sum: 0.40
  gore_any: 0.30
  nsfw_margin_min: 0.00
  nsfw_ratio_min: 0.45
  nsfw_general_sum: 0.20
  exposure_mid: 0.30
  exposure_strong: 0.60
  exposure_risk: 0.60
  yellow_minor_hint: 0.20
  sexual_explicit_sum_med: 0.10
  sexual_explicit_sum_high: 0.15
  sexual_modifier_sum_min: 0.10
  animal_subject_min: 0.35
  minor_peak_min: 0.20
  gore_peak_min: 0.30
  gore_sum_min: 0.40
  dismember_peak_min: 0.20
  mild_exposure_peak_min: 0.30
  drug_any_min: 0.15

minor_tags:
  - loli
  - shota
  - child
  - kid
  - newborn
  - baby
  - infant
  - toddler
  - preteen
  - teen
  - young
  - younger
  - adolescent
  - little_girl
  - little_boy
  - schoolgirl
  - schoolboy
  - school_uniform
  - randoseru
  - flat_chest
  - small_breasts
  - chibi

violence_tags:
  - gore
  - blood
  - guts
  - wound
  - severed_arm
  - severed_leg
  - severed_head
  - decapitation
  - disembowelment
  - dismemberment
  - guro
  - ryona
  - death
  - corpse
  - injury
  - cuts
  - bruise
  - scar
  - torture
  - whipping
  - burn
  - murder
  - strangulation
  - asphyxiation
  - drowning
  - electrocution
  - poison
  - stab
  - slash
  - gunshot
  - cannibalism
  - vore
  - mutilation
  - necrophilia
  - abuse
  - bullying
  - rape
  - execution
  - war
  - drug
  - pill
  - syringe
  - injection
  - marijuana
  - cocaine
  - heroin
  - meth
  - lsd
  - addiction

nsfw_general_tags:
  - nude
  - topless
  - bottomless
  - nipples
  - penis
  - testicles
  - pussy
  - clitoris
  - cameltoe
  - cleft_of_venus
  - futanari
  - anus
  - pubic_hair
  - uncensored
  - censored
  - mosaic_censoring
  - cum
  - pussy_juice
  - pee
  - scat
  - sex
  - vaginal
  - anal
  - oral
  - paizuri
  - fellatio
  - cunnilingus
  - penetration
  - masturbation
  - ejaculation
  - orgasm
  - group_sex
  - gangbang
  - orgy
  - rape
  - bondage
  - sex_toy
  - dildo
  - vibrator
  - object_insertion
  - bdsm
  - spanking
  - collar
  - leash
  - slave
  - lactation
  - pregnant

animal_abuse_tags:
  - animal_abuse
  - animal_cruelty
  - animal_blood
  - animal_gore
  - bestiality
  - zoophilia
  - zoosadism
  - animal_harm
  - animal_torture
  - dead_animal
  - taxidermy
  - animal_fight
  - animal_trap
  - animal_starvation
  - animal_neglect
  - feral_abuse
  - furry_bestiality
  - yiff
  - animal_corpse
  - hunting
  - dog
  - cat
  - horse
  - bird
  - rabbit
  - cow
  - pig
  - snake
  - insect
  - furry
  - wolf
  - fox
  - lion
  - tiger
  - bear
  - deer
  - sheep
  - goat
  - fish
  - reptile
  - amphibian
  - rodent
  - monkey
  - elephant
  - dragon
  - unicorn
  - pokemon
  - anthro
  - kemono

xsignals_weights:
  exposure_strong_weight: 1.0
  exposure_weak_weight: 0.6
  placement_rating_weight: 0.5
  placement_general_weight: 0.3
  placement_exposure_weight: 0.7
  placement_general_topk: 3

severity_priority:
  red: 3
  orange: 2
  yellow: 1
