version: 2
dsl_mode: warn

rule_titles:
  RED-201: "暴力・グロが疑われる"
  RED-301: "未成年の性的描写が疑われる"
  ORANGE-101: "18+でないチャンネルの成人向けコンテンツ"
  YELLOW-101: "軽度の露出"
  YELLOW-201: "若年寄りの特徴を含む"
  RED-NSFW-101: "非NSFWチャンネルの性的表現"
  RED-MINOR-SEX-201: "未成年×性的"
  RED-MINOR-GORE-202: "未成年×流血/損壊"
  RED-ANIMAL-SEX-301: "動物×性的/獣姦"
  RED-ANIMAL-GORE-302: "動物×虐待/流血"
  RED-DISMEMBER-BLOOD-401: "欠損×出血"
  ORANGE-ADULT-SEX-DRUG-501: "成人×性的×薬物"
  ORANGE-MINOR-MILD-601: "未成年×軽微露出"

groups:
  nsfw_general:
    - nipples
    - nipple_slip
    - nipple_tweak
    - areola_slip
    - pussy
    - pussy_peek
    - clitoris
    - penis
    - penis_peek
    - testicles
    - anus
    - anus_peek
    - nude
    - completely_nude
    - rape
    - molestation
    - sleep_molestation
    - chikan
    - humiliation
    - rough_sex
    - ryona
    - bondage
    - restrained
    - asphyxiation
    - public_use
    - spanked
    - torture
    - abuse
    - bullying
    - groping
    - strangling
    - loli
    - shota
    - small_nipples
    - small_penis
    - cleft_of_venus
    - bestiality
    - animal_penis
    - dog_penis
    - horse_penis
    - knotted_penis
    - pokephilia
    - '69'
    - anal
    - anilingus
    - ass
    - bondage
    - bottomless
    - boy_on_top
    - breast_sucking
    - bukkake
    - buttjob
    - cameltoe
    - clothed_masturbation
    - condom
    - cowgirl_position
    - cum
    - cumdrip
    - cunnilingus
    - deepthroat
    - dildo
    - doggystyle
    - double_handjob
    - double_penetration
    - ejaculation
    - facial
    - fellatio
    - femdom
    - fingering
    - footjob
    - frottage
    - futanari
    - gag
    - gangbang
    - girl_on_top
    - gokkun
    - groping
    - group_sex
    - guided_penetration
    - hairjob
    - handjob
    - inflation
    - irrumatio
    - large_insertion
    - masturbation
    - mating_press
    - missionary
    - mutual_masturbation
    - no_bra
    - no_panties
    - object_insertion
    - oral
    - orgy
    - paizuri
    - pee
    - prone_bone
    - pubic_hair
    - pussy_juice
    - reach-around
    - reverse_cowgirl_position
    - reverse_suspended_congress
    - reverse_upright_straddle
    - sex
    - sex_from_behind
    - sex_toy
    - shibari
    - spitroast
    - stomach_bulge
    - strangling
    - strap-on
    - suspended_congress
    - tentacle_sex
    - testicle_sucking
    - thigh_sex
    - threesome
    - upright_straddle
    - urethral_insertion
    - vibrator
    - vaginal
  minors:
    - adolescent
    - baby
    - chibi
    - child
    - flat_chest
    - infant
    - kid
    - little_boy
    - little_girl
    - loli
    - newborn
    - preteen
    - randoseru
    - school_uniform
    - schoolboy
    - schoolgirl
    - shota
    - small_breasts
    - teen
    - toddler
    - young
    - younger
  violence:
    - abuse
    - bullying
    - strangulation
    - torture
    - whipping
    - burn
    - bruise
    - scar
    - wound
    - cuts
    - slash
    - stab
    - gunshot
    - war
    - murder
    - death
    - corpse
    - decapitation
    - dismemberment
    - severed_arm
    - severed_head
    - severed_leg
    - disembowelment
    - cannibalism
    - mutilation
    - gore
    - guts
    - blood
    - vore
    - asphyxiation
    - drowning
    - electrocution
    - poison
    - execution
    - ryona
    - guro
    - necrophilia
    - addiction
    - cocaine
    - heroin
    - lsd
    - marijuana
    - meth
    - drug
    - pill
    - syringe
    - injection
  gore:
    - blood
    - gore
    - guts
    - wound
    - severed_arm
    - severed_head
    - severed_leg
    - decapitation
    - disembowelment
    - dismemberment
    - corpse
    - bruise
    - scar
    - injury
  drugs:
    - drug
    - drugs
    - marijuana
    - cocaine
    - heroin
    - meth
    - lsd
    - pill
    - syringe
    - injection
    - addiction
    - poison
  animal_subjects:
    - amphibian
    - bear
    - bird
    - cat
    - cow
    - deer
    - dog
    - dragon
    - elephant
    - fish
    - fox
    - furry
    - goat
    - horse
    - insect
    - kemono
    - lion
    - monkey
    - pig
    - pokemon
    - rabbit
    - reptile
    - rodent
    - sheep
    - snake
    - tiger
    - unicorn
    - wolf
  animal_contexts:
    - animal_abuse
    - animal_corpse
    - animal_cruelty
    - animal_gore
    - animal_harm
    - animal_neglect
    - animal_starvation
    - animal_torture
    - animal_trap
    - animal_fight
    - animal_blood
    - bestiality
    - zoophilia
    - zoosadism
    - dead_animal
    - feral_abuse
    - furry_bestiality
    - hunting
    - taxidermy
    - yiff

features:
  nsfw_margin: "max(rating.explicit, rating.questionable) - max(rating.general, rating.sensitive)"
  nsfw_ratio: "(rating.explicit + rating.questionable) / clamp(rating.explicit + rating.questionable + rating.general + rating.sensitive, 1e-6, 1e6)"
  nsfw_general_sum: "sum('nsfw_general')"
  violence_sum: "sum('violence')"
  violence_max: "max('violence')"
  minors_sum: "sum('minors')"
  minors_max: "max('minors')"
  animals_sum: "sum('animal_subjects') + sum('animal_contexts')"
  animals_max: "max('animal_subjects')"
  gore_sum: "sum('gore')"
  gore_max: "max('gore')"
  drug_score: "sum('drugs')"
  animal_combo: "max('animal_contexts') * max('animal_subjects')"

rules:
  - id: ORANGE-101
    severity: orange
    priority: 10
    when: "(!channel.is_nsfw) && (nsfw_margin >= 0.10 || any('nsfw_general', gt=0.35))"
    reasons:
      - "margin={nsfw_margin:.2f}"
      - "general={nsfw_general_sum:.2f}"
  - id: RED-ANIMAL-GORE-302
    severity: red
    priority: 20
    when: "max('animal_contexts') >= 0.25 || (animal_combo >= 0.04)"
    reasons:
      - "context={max('animal_contexts'):.2f}"
      - "combo={animal_combo:.2f}"
    stop: true
