version: 2
dsl_mode: warn
rule_titles:
  C-RED-001: 非合意の性的描写
  A-RED-001: 未成年×性的（厳重警告）
  A-YEL-001: 要確認：幼い体型＋性的文脈
  B-RED-NSFW-001: 非NSFWチャンネルの露骨な性表現
  B-ORG-001: 非NSFWチャンネルの性的コンテンツ
  D-RED-001: 性的文脈を伴うゴア
  D-ORG-001: ショッキングな流血・損壊
  E-RED-001: 獣姦タグ検出
  E-YEL-001: 動物＋性的文脈（要レビュー）
groups:
  explicit_nudity:
  - nipples
  - nipple_slip
  - areola_slip
  - pussy
  - pussy_peek
  - clitoris
  - penis
  - penis_peek
  - testicles
  - anus
  - anus_peek
  - nude
  - completely_nude
  sexual_act_lexicon:
  - after_anal
  - after_fellatio
  - after_masturbation
  - after_paizuri
  - after_sex
  - after_vaginal
  - afterglow
  - ahegao
  - anal
  - anal_beads
  - anal_fingering
  - anal_object_insertion
  - anal_tail
  - anilingus
  - armpit_sex
  - artificial_vagina
  - assertive_female
  - ball_gag
  - bdsm
  - big_belly
  - bit_gag
  - blindfold
  - bondage
  - bondage_outfit
  - bound_arms
  - bound_legs
  - bound_wrists
  - boy_on_top
  - breast_bondage
  - breast_expansion
  - breast_smother
  - breast_sucking
  - breastfeeding
  - bukkake
  - bust_cup
  - butt_plug
  - buttjob
  - caressing_testicles
  - caught
  - chain
  - cleave_gag
  - clothed_female_nude_male
  - clothed_masturbation
  - clothed_sex
  - collar
  - condom
  - cooperative_fellatio
  - cooperative_paizuri
  - cowgirl_position
  - cross-section
  - crotch_grab
  - crotch_rope
  - crotch_rub
  - cuffs
  - cum
  - cum_in_ass
  - cum_in_clothes
  - cum_in_mouth
  - cum_in_pussy
  - cum_inflation
  - cum_on_ass
  - cum_on_body
  - cum_on_breasts
  - cum_on_clothes
  - cum_on_eyewear
  - cum_on_feet
  - cum_on_hair
  - cum_on_pectorals
  - cum_on_pussy
  - cum_on_stomach
  - cum_on_tongue
  - cum_pool
  - cumdrip
  - cunnilingus
  - deep_penetration
  - deepthroat
  - diaper
  - dildo
  - dildo_riding
  - doggystyle
  - double_dildo
  - double_handjob
  - double_penetration
  - egg_vibrator
  - ejaculating_while_penetrated
  - ejaculation
  - exhibitionism
  - facial
  - fellatio
  - female_ejaculation
  - female_masturbation
  - femdom
  - fff_threesome
  - ffm_threesome
  - fingering
  - fingering_through_clothes
  - fingering_through_panties
  - foot_worship
  - footjob
  - frogtie
  - frottage
  - fucked_silly
  - full-package_futanari
  - full_nelson
  - futa_on_male
  - futa_with_female
  - futa_with_futa
  - futa_with_male
  - futanari
  - futanari_masturbation
  - futasub
  - gag
  - gag_harness
  - gangbang
  - girl_on_top
  - glory_wall
  - gokkun
  - grinding
  - group_sex
  - guided_breast_grab
  - guided_penetration
  - hairjob
  - handcuffs
  - handjob
  - happy_sex
  - have_to_pee
  - hitachi_magic_wand
  - hogtie
  - huge_dildo
  - imminent_anal
  - imminent_penetration
  - imminent_vaginal
  - implied_fellatio
  - implied_fingering
  - implied_futanari
  - implied_masturbation
  - implied_sex
  - impregnation
  - inflation
  - internal_cumshot
  - irrumatio
  - lactation
  - lactation_through_clothes
  - large_insertion
  - leash
  - leash_pull
  - licking_foot
  - lotion
  - lotion_bottle
  - lube
  - male_masturbation
  - masturbation
  - mating_press
  - milking_machine
  - missionary
  - mmf_threesome
  - mmm_threesome
  - mutual_masturbation
  - naughty_face
  - newhalf
  - nipple_chain
  - nipple_clamps
  - nipple_pull
  - nipple_tweak
  - no_testicles
  - nursing_handjob
  - object_insertion
  - oral
  - orgy
  - paizuri
  - paizuri_under_clothes
  - peeing
  - peeing_self
  - peeking
  - penises_touching
  - perpendicular_paizuri
  - pet_play
  - piercing
  - pregnant
  - prone_bone
  - prostitution
  - public_indecency
  - public_nudity
  - pussy_juice
  - reach-around
  - remote_control_vibrator
  - reverse_cowgirl_position
  - reverse_suspended_congress
  - reverse_upright_straddle
  - riding_crop
  - ring_gag
  - rope
  - sex
  - sex_from_behind
  - sex_machine
  - sex_toy
  - shackles
  - shibari
  - shibari_over_clothes
  - sitting_on_face
  - spanked
  - spitroast
  - spooning
  - spreader_bar
  - stomach_bulge
  - straddling_paizuri
  - strap-on
  - suspended_congress
  - suspension
  - table_humping
  - take_your_pick
  - tape_gag
  - teamwork
  - testicle_sucking
  - thigh_sex
  - threesome
  - torogao
  - tribadism
  - triple_penetration
  - two-handed_handjob
  - upright_straddle
  - urethral_insertion
  - used_condom
  - used_condom_on_penis
  - vaginal
  - vaginal_object_insertion
  - vibrator
  - vibrator_in_thighhighs
  - vibrator_on_nipple
  - vibrator_under_clothes
  - vibrator_under_panties
  - voyeurism
  - wakamezake
  - whip
  - x-ray
  sexual_context_boosters:
  - adjusting_clothes
  - babydoll
  - backless_outfit
  - bikini_pull
  - bodystocking
  - camisole
  - cleavage
  - cleavage_cutout
  - clothes_down
  - clothes_grab
  - clothing_aside
  - corset
  - covering_breasts
  - covering_crotch
  - dress_lift
  - dress_pull
  - fishnets
  - garter_belt
  - garter_straps
  - g-string
  - lace
  - latex
  - lingerie
  - panty_pull
  - see-through
  - strap_slip
  - thighhighs
  - thong
  - underboob
  - undressing
  - unzipped
  - wet_clothes
  - wet_shirt
  coercion_main:
  - rape
  - molestation
  - sleep_molestation
  - imminent_rape
  - after_rape
  - chikan
  - humiliation
  - rough_sex
  - ryona
  - stealth_sex
  coercion_sub:
  - bondage
  - restrained
  - asphyxiation
  - public_use
  - spanked
  - torture
  - abuse
  - bullying
  - groping
  - strangling
  unconscious_states:
  - unconscious
  - drugged
  - drunk
  - sleeping
  - hypnosis
  - mind_control
  pain_expressions:
  - pain
  - struggling
  - crying
  - scared
  - trembling
  - embarrassed
  - wince
  - angry
  restraint_gear:
  - collar
  - chain
  - rope
  - cuffs
  - leash
  - blindfold
  - gag
  - shackles
  - handcuffs
  - ball_gag
  - whip
  - crotch_rope
  - riding_crop
  - bit_gag
  - tape_gag
  - bondage_outfit
  - spreader_bar
  - nipple_clamps
  - ring_gag
  - cleave_gag
  - nipple_chain
  - gag_harness
  - hogtie
  minor_peak:
  - loli
  - shota
  - child
  - baby
  minor_body_high:
  - petite
  - aged_down
  minor_body_medium:
  - flat_chest
  - small_breasts
  - flat_ass
  - slim_legs
  - small_nipples
  - small_penis
  - cleft_of_venus
  minor_body_special:
  - oppai_loli
  - shortstack
  minor_situation_high:
  - child_on_child
  minor_situation_other:
  - onee-shota
  - onii-shota
  - onee-loli
  minor_situation_medium:
  - incest
  - age_difference
  - size_difference
  - penis_size_difference
  minor_uniforms:
  - school_uniform
  - serafuku
  - gakuran
  - uwabaki
  - kindergarten_uniform
  - gym_uniform
  - school_swimsuit
  - randoseru
  - school_bag
  minor_school_context:
  - classroom
  - school_desk
  - school_chair
  - gym_storeroom
  gore_peak:
  - guro
  - decapitation
  - severed_head
  - severed_limb
  - amputee
  - double_amputee
  - self-harm
  - suicide
  - corpse
  - death
  - impaled
  - stab
  blood_tags:
  - blood
  - bleeding
  - blood_on_face
  - blood_on_clothes
  - blood_on_hands
  - blood_on_weapon
  - blood_on_ground
  - blood_in_hair
  - blood_on_bandages
  - blood_on_arm
  - blood_on_leg
  - blood_stain
  - nosebleed
  - pool_of_blood
  - ambiguous_red_liquid
  injury_tags:
  - bruise
  - cuts
  - scratches
  - stitches
  - scar
  - bruise_on_face
  - injury
  death_markers:
  - empty_eyes
  - crying_with_eyes_open
  - no_pupils
  animal_subjects:
  - animal
  - bird
  - cat
  - dog
  - rabbit
  - snake
  - frog
  - horse
  - mouse
  - wolf
  - fox
  - bear
  - tiger
  - sheep
  - panda
  - pig
  - hamster
  - whale
  - turtle
  - squirrel
  - lion
  - monkey
  - dolphin
  - deer
  - cow
  - hedgehog
  - boar
  - elephant
  - puppy
  - ferret
  - goat
  - lizard
  - orca
  - bat_(animal)
  - seal_(animal)
  bestiality_direct:
  - bestiality
  - animal_penis
  - dog_penis
  - horse_penis
  - knotted_penis
  - pokephilia
features:
  nsfw_rating_max: max(rating.sensitive, rating.questionable, rating.explicit)
  explicit_score: max('explicit_nudity')
  sexual_intensity: topk_sum('sexual_act_lexicon', k=3, gt=0.35) + 0.5 * topk_sum('sexual_context_boosters',
    k=3, gt=0.35)
  coercion_score: clamp(max('coercion_main') / 0.2, 0, 1) + clamp(count('coercion_sub',
    gt=0.35), 0, 2) * 0.5 + clamp(max('unconscious_states') / 0.2, 0, 1) * 0.5 + clamp(count('pain_expressions',
    gt=0.2) / 2, 0, 1) * 0.5 + clamp(topk_sum('restraint_gear', k=3, gt=0.2) / 0.6,
    0, 1) * 0.5
  minor_peak_conf: max('minor_peak')
  minor_body_score: max('minor_body_high') + 0.5 * topk_sum('minor_body_medium', k=3,
    gt=0.3)
  minor_context_score: max('minor_situation_high') + 0.5 * topk_sum('minor_situation_other',
    k=2, gt=0.3) + 0.25 * topk_sum('minor_situation_medium', k=3, gt=0.3) + 0.25 *
    (count('minor_uniforms', gt=0.35) + count('minor_school_context', gt=0.35))
  minor_special_score: max('minor_body_special')
  gore_peak_conf: max('gore_peak')
  gore_density: count('blood_tags', gt=0.35) + count('injury_tags', gt=0.35)
  gore_intensity: max('gore_peak') + 0.5 * (count('blood_tags', gt=0.35) + count('injury_tags',
    gt=0.35)) + 0.5 * sum('pain_expressions')
  animal_presence: max('animal_subjects')
  animal_score: sum('animal_subjects')
rules:
- id: C-RED-001
  severity: red
  priority: 100
  when: sexual_intensity >= 0.5 && coercion_score >= 1.0
  reasons:
  - sexual={sexual_intensity:.2f}
  - coercion={coercion_score:.2f}
  stop: true
- id: A-RED-001
  severity: red
  priority: 90
  when: (minor_peak_conf >= 0.3 || minor_body_score >= 0.7 || minor_context_score
    >= 0.8) && (sexual_intensity >= 0.3 || explicit_score >= 0.3 || exposure_area
    >= 0.2 || exposure_count >= 2)
  reasons:
  - minor_peak={minor_peak_conf:.2f}
  - minor_body={minor_body_score:.2f}
  - sex={sexual_intensity:.2f}
  stop: true
- id: A-YEL-001
  severity: yellow
  priority: 80
  when: minor_special_score >= 0.35 && (sexual_intensity >= 0.2 || explicit_score
    >= 0.2 || exposure_area >= 0.1)
  reasons:
  - minor_special={minor_special_score:.2f}
  - sex={sexual_intensity:.2f}
- id: B-RED-NSFW-001
  severity: red
  priority: 70
  when: (!channel.is_nsfw) && (explicit_score >= 0.5 || sexual_intensity >= 0.8 ||
    exposure_area >= 0.2)
  reasons:
  - explicit={explicit_score:.2f}
  - sexual={sexual_intensity:.2f}
  - exposure={exposure_area:.2f}
  stop: true
- id: B-ORG-001
  severity: orange
  priority: 60
  when: (!channel.is_nsfw) && (sexual_intensity >= 0.4 || nsfw_rating_max >= 0.5 ||
    exposure_area >= 0.15)
  reasons:
  - sexual={sexual_intensity:.2f}
  - rating={nsfw_rating_max:.2f}
  - exposure={exposure_area:.2f}
- id: D-RED-001
  severity: red
  priority: 55
  when: (gore_peak_conf >= 0.2 || gore_intensity >= 2.5) && sexual_intensity >= 0.3
  reasons:
  - gore={gore_intensity:.2f}
  - sexual={sexual_intensity:.2f}
  stop: true
- id: D-ORG-001
  severity: orange
  priority: 50
  when: gore_peak_conf >= 0.2 || gore_density >= 3 || gore_intensity >= 2.0
  reasons:
  - gore={gore_intensity:.2f}
  - density={gore_density}
- id: E-RED-001
  severity: red
  priority: 45
  when: max('bestiality_direct') >= 0.2
  reasons:
  - bestiality={max('bestiality_direct'):.2f}
  stop: true
- id: E-YEL-001
  severity: yellow
  priority: 40
  when: animal_presence >= 0.3 && sexual_intensity >= 0.3
  reasons:
  - animals={animal_presence:.2f}
  - sexual={sexual_intensity:.2f}
