exposure_score:
  strong_weight: 1.0
  weak_weight: 0.6
placement_risk_pre:
  rating_weight: 0.5
  general_weight: 0.3
  exposure_weight: 0.7
  topk: 3
  nsfw_tags:
  - nude
  - topless
  - bottomless
  - nipples
  - penis
  - testicles
  - pussy
  - clitoris
  - cameltoe
  - cleft_of_venus
  - futanari
  - anus
  - pubic_hair
  - uncensored
  - censored
  - mosaic_censoring
  - cum
  - pussy_juice
  - pee
  - scat
  - sex
  - vaginal
  - anal
  - oral
  - paizuri
  - fellatio
  - cunnilingus
  - penetration
  - masturbation
  - ejaculation
  - orgasm
  - group_sex
  - gangbang
  - orgy
  - rape
  - bondage
  - sex_toy
  - dildo
  - vibrator
  - object_insertion
  - bdsm
  - spanking
  - collar
  - leash
  - slave
  - lactation
  - pregnant
