name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pytest
        run: pytest -q --cov=app --cov-report=xml --cov-fail-under=65 -m "not slow and not wd14_heavy"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: warn

      - name: Upload metrics artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pipeline-metrics
          path: |
            out/metrics/*.json
            out/exports/*.csv
          if-no-files-found: ignore

  wd14-heavy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run WD14 heavy tests
        run: pytest -q -m wd14_heavy
